language: node_js

node_js:
  - node # will use latest node


addons:
  chrome: stable

before_script: # commands to run before the build step
  - npm install -g --silent @angular/cli
  - npm install


script: # the build step
  - npm test
  - ng build --prod

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   